sudo: required

services:
  - docker

language: generic

script:
  - docker build -t zbeekman/docker-gcc-build:latest . | tee build.log

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push zbeekman/docker-gcc-build;
    fi
