#!/bin/bash
# See https://github.com/rossf7/label-schema-automated-build
#     or https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1#.wgkzfdnfr
#     for more details.

# $IMAGE_NAME var is injected into the build so the tag is correct.

set -o verbose
set -o pipefail
set -o errexit

d_repo='zbeekman/nightly-gcc-trunk-docker-image'

echo "Build hook running"
docker build --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --build-arg VCS_REF="${SOURCE_COMMIT:-$(git rev-parse --short HEAD)}" \
             --build-arg VCS_URL="$(git remote get-url --all origin || echo "https://github.com/${DOCKER_REPO:-${d_repo}}")" \
             -t "${IMAGE_NAME:-${d_repo}:latest}" .
