#!/bin/bash

echo "Build hook running"
docker build --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --build-arg SOURCE_BRANCH="$SOURCE_BRANCH" \
             --build-arg SOURCE_COMMIT="$SOURCE_COMMIT" \
             --build-arg IMAGE_NAME="$IMAGE_NAME" \
              -t $IMAGE_NAME .
