#!/bin/bash
# See https://github.com/rossf7/label-schema-automated-build
#     or https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1#.wgkzfdnfr
#     for more details.

# $IMAGE_NAME var is injected into the build so the tag is correct.

set -o verbose
set -o pipefail
set -o errexit

echo "Build hook running"
docker build --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
             --build-arg VCS_REF=$(git rev-parse --short HEAD) \
             -t ${IMAGE_NAME:-zbeekman/docker-gcc-build} .
